# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
    redirect.after.login:
        class : Myapp\UserBundle\Redirection\AfterLoginRedirection
        arguments: ["@router"]

    redirectionListener:
          class: Eshop\StockBundle\Listener\RedirectionListener
          arguments: ["@service_container","@session"]
          tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    setNewReference:
                  class: Eshop\StockBundle\Services\GetReference
                  arguments: ["@doctrine.orm.entity_manager"]