supprimer:
    path:  /supprimer/{id}
    defaults: { _controller: EshopStockBundle:Panier:supprimer}

ajouter:
    path:  /ajouter/{id}
    defaults: { _controller: EshopStockBundle:Panier:ajouter}

panier:
    path:  /panier
    defaults: { _controller: EshopStockBundle:Panier:panier}
